spring:
  application:
    name: "Jdbc-multi-datasource"
  datasource:
    tomcat:
      initial-size: 15
      max-wait: 20000
      max-active: 50
      max-idle: 10
      min-idle: 5
      default-auto-commit: true
    type: org.apache.tomcat.jdbc.pool.DataSource
    username: "act_admin"
    url: jdbc:sqlserver://localhost:1433;databaseName=testmaster
    jdbcUrl: jdbc:sqlserver://localhost:1433;databaseName=testmaster
    password: "Password1"
    test-on-borrow: true
    validation-query: SELECT 1
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver